# Generated by Django 3.0 on 2019-12-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django101', '0002_auto_20191204_0838'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='power',
            table='powers',
        ),
    ]
