# Generated by Django 3.0 on 2019-12-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='superhero',
            table='superheroes',
        ),
    ]
